### ISSUE TITLE
Please provide a proper code repo

### ISSUE THREAD

**Issue by pcav** [andresgciamtez/wnt#1]
not a zip, but the code as text, with a revision control.
Thanks.

**Comment by andresgciamtez** [comment]
I uploaded all the code.
Cheers.

**Comment by pcav** [comment]
Thanks. I believe the organization of directories could be better, could you please have a lok to other similar plugins? The code could be in the root dir, no need for a subdir, and the doc dir at the top level seems useless.
Cheers.

**Comment by andresgciamtez** [comment]
I reorganized and delete. Any suggestion for revision control?
Cheers.

**Comment by pcav** [comment]
Looks OK to me, thanks.
