### ISSUE TITLE
Please add a more comprehensive description

### ISSUE THREAD

**Issue by pcav** [andresgciamtez/wnt#2]
thanks

**Comment by andresgciamtez** [comment]
now, is it ok?

**Comment by pcav** [comment]
I meant the description in metadata, that appears here:
http://plugins.qgis.org/plugins/wnt/
still very short, it does not help much an user to decide whether to install it or not

**Comment by andresgciamtez** [comment]
Updated:
metadata.txt
and
http://plugins.qgis.org/plugins/wnt/

**Comment by andresgciamtez** [comment]
This was solved
