### ISSUE TITLE
Graph from network

### ISSUE THREAD

**Issue by Jannik-Schilling** [andresgciamtez/wnt#4]
Update: as I didn´t find "wnt_graph_from_network.py" in the repository an longer I renamed the Issue to Network from lines.

It seems the algorithm cannot deal with MultiLineStrings. [with "Multipart to singleparts" it works...until:]

wnt_network_from_lines.py", line 277, in processAlgorithm
length = link.get_length2d()
AttributeError: 'Link' object has no attribute 'get_length2d'

**Comment by andresgciamtez** [comment]
. \ wnt \ wnt_graph_from_network.py ", line 140, in processAlgorithm
n.nodes.append (tools.Node (f ['id']))
KeyError: 'id'
Are the input layers of Graph_from_network?
- A layer of nodes with assigned id field
- A layer of links with assigned id, start and end fields
Please, check it. If you still have problems send me the 2 layers.

Avoid using MultiLineStrings to not form discontinuous links.

**Comment by Jannik-Schilling** [comment]
Do I already need a line layer with "id", "start" and "end" fields as input to "wnt_network_from_lines.py"?

**Comment by andresgciamtez** [comment]
No. The fields are not necessary to build a network by means of wnt_network_from_lines.py".
The fields are necessary to construct the graph by means of "wnt_Graph_from_network.py".

**Comment by Jannik-Schilling** [comment]
finally it worked. there´s still one bug in your code: in line 277 of wnt_network_from_lines.py you have to replace `length = link.get_length2d()` by `length = link.length2d()` as defined in tools.py

**Comment by andresgciamtez** [comment]
Thanks you!
