### ISSUE TITLE
Please remove binaries

### ISSUE THREAD

**Issue by pcav** [andresgciamtez/wnt#6]
Only source code is acceptable.
Thanks.

**Comment by andresgciamtez** [comment]
I removed binaries in v0.3.3. Could you check it? Please

**Comment by pcav** [comment]
Thanks, published.
Could you please remove older versions containing binaries?
Cheers.

On 13 November 2019 10:47:27 EET, andresgciamtez <notifications@github.com> wrote:
>I removed binaries in v0.3.3. Could you check it? Please
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andresgciamtez/wnt/issues/6#issuecomment-553300335

-- 
Please excuse my brevity.

**Comment by andresgciamtez** [comment]
I removed v0.3.2 (plugins.qgis.org/plugins/wnt/), neither v0.1 nor v0.2 contains binaries. So, it is corrected?

**Comment by pcav** [comment]
Perfect, thanks.

On 13 November 2019 13:03:39 EET, andresgciamtez <notifications@github.com> wrote:
>I removed v0.3.2 (plugins.qgis.org/plugins/wnt/), neither v0.1 nor v0.2
>contains binaries. So, it is corrected?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andresgciamtez/wnt/issues/6#issuecomment-553353897

-- 
Please excuse my brevity.
